sudo: required
dist: trusty
language: cpp
compiler: g++
script: ./configure && make -C build
install: export CXX="g++-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5